/*
 * bchanl_panels.h
 *
 * Copyright (c) 2012 project bchan
 *
 * This software is provided 'as-is', without any express or implied
 * warranty. In no event will the authors be held liable for any damages
 * arising from the use of this software.
 *
 * Permission is granted to anyone to use this software for any purpose,
 * including commercial applications, and to alter it and redistribute it
 * freely, subject to the following restrictions:
 *
 * 1. The origin of this software must not be misrepresented; you must not
 *    claim that you wrote the original software. If you use this software
 *    in a product, an acknowledgment in the product documentation would be
 *    appreciated but is not required.
 *
 * 2. Altered source versions must be plainly marked as such, and must not be
 *    misrepresented as being the original software.
 *
 * 3. This notice may not be removed or altered from any source
 *    distribution.
 *
 */

/* This file is automatically generated. */

#include    <basic.h>
#include	<btron/dp.h>
#include	<btron/hmi.h>

#ifndef __BCHANL_PANELS_H__
#define __BCHANL_PANELS_H__

enum BCHAN_PANELS_SAVECONFIRM_RESULT_ {
	BCHAN_PANELS_SAVECONFIRM_RESULT_CANCEL,
	BCHAN_PANELS_SAVECONFIRM_RESULT_OK_NOSAVE,
	BCHAN_PANELS_SAVECONFIRM_RESULT_OK_SAVE,
};
typedef enum BCHAN_PANELS_SAVECONFIRM_RESULT_ BCHAN_PANELS_SAVECONFIRM_RESULT;

IMPORT BCHAN_PANELS_SAVECONFIRM_RESULT bchan_panels_saveconfirm();

enum BCHAN_PANELS_URLERROR_SCHEME_RESULT_ {
	BCHAN_PANELS_URLERROR_SCHEME_RESULT_OK,
};
typedef enum BCHAN_PANELS_URLERROR_SCHEME_RESULT_ BCHAN_PANELS_URLERROR_SCHEME_RESULT;

IMPORT BCHAN_PANELS_URLERROR_SCHEME_RESULT bchan_panels_urlerror_scheme();

enum BCHAN_PANELS_URLERROR_HOST_RESULT_ {
	BCHAN_PANELS_URLERROR_HOST_RESULT_OK,
};
typedef enum BCHAN_PANELS_URLERROR_HOST_RESULT_ BCHAN_PANELS_URLERROR_HOST_RESULT;

IMPORT BCHAN_PANELS_URLERROR_HOST_RESULT bchan_panels_urlerror_host();

enum BCHAN_PANELS_URLERROR_PATH_RESULT_ {
	BCHAN_PANELS_URLERROR_PATH_RESULT_OK,
};
typedef enum BCHAN_PANELS_URLERROR_PATH_RESULT_ BCHAN_PANELS_URLERROR_PATH_RESULT;

IMPORT BCHAN_PANELS_URLERROR_PATH_RESULT bchan_panels_urlerror_path();

#endif
